# AppVeyor CI configuration:

# We don't do a shallow clone of just the source archive as we want to get
# the diff for source file checks.
# We do limit to the last few commits to speed things up:
clone_depth: 10

# Don't run on pushes to feature branches: pull requests cover those.
branches:
  only:
    - master

platform: x64

build:
  parallel: true 

environment:
  matrix:
    - GENERATOR: Visual Studio 12
      CONFIG: Debug
      DEBUG_FLAG: ON
      MSVC_PLATFORM: x86

    - GENERATOR: Visual Studio 12
      CONFIG: RelWithDebInfo
      DEBUG_FLAG: OFF
      MSVC_PLATFORM: x86

    - GENERATOR: Visual Studio 12 Win64
      CONFIG: Debug
      DEBUG_FLAG: ON
      MSVC_PLATFORM: x86_amd64
      
    - GENERATOR: Visual Studio 12 Win64
      CONFIG: RelWithDebInfo
      DEBUG_FLAG: OFF
      MSVC_PLATFORM: x86_amd64

before_build:
  - call "c:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %MSVC_PLATFORM%
  - cd c:\projects\drltrace
  - git submodule update --init --recursive
  - mkdir build
  - cd build 

build_script:
  #parallel: true
  - cmake "-G%GENERATOR%" -DDEBUG=%DEBUG_FLAG% -DBUILD_TOOL_TESTS=ON ..\drltrace_src\
  - cmake --build . --config "%CONFIG%"

test_script:
  - ctest -VV
